=== apache/ofbiz-plugins/ofbiz-rest-impl/dtd/rest-api.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<!-- NOTE: files using this schema are found in the service directory in a component when named *.rest.xml -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified">
    <xs:element name="api">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="resource"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="displayName" type="xs:string"/>
            <xs:attribute name="description" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="resource">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="operation"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="path" type="xs:string" use="required"/>
            <xs:attribute name="displayName" type="xs:string"/>
            <xs:attribute name="description" type="xs:string"/>
            <xs:attribute name="publish" type="xs:boolean" default="true"/>
            <xs:attribute name="auth" type="xs:boolean" default="true"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="operation">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="1" ref="service"/>
            </xs:sequence>
            <xs:attribute name="verb" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="get"/>
                        <xs:enumeration value="patch"/>
                        <xs:enumeration value="put"/>
                        <xs:enumeration value="post"/>
                        <xs:enumeration value="delete"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="produces" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="application/xml"/>
                        <xs:enumeration value="application/json"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="consumes" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="application/xml"/>
                        <xs:enumeration value="application/json"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="path" type="xs:string" use="optional"/>
            <xs:attribute name="description" type="xs:string"/>
            <xs:attribute name="auth" type="xs:boolean" default="true"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="service">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== apache/ofbiz-plugins/headless-commerce/api/headless-commerce.rest.xml
<api description="Customers API" displayName="Customers API" name="CustomersAPI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rest-api.xsd">
  <resource description="" displayName="" enabled="true" name="Customers Resource" path="/hcv1/customers">
    <operation verb="post" description="Creates Customer">
      <service name="createCustomer"/>
    </operation>
    <operation verb="get" path="/{customerPartyId}/" description="Retrieves customer profile">
      <service name="getCustomer"/>
    </operation>
    <operation verb="put" path="/{customerPartyId}" description="Updates customer's personal information">
      <service name="updatePerson"/>
    </operation>
    <operation verb="get" path="/{customerPartyId}/shipping-addresses" description="Retrieves shipping addresses">
      <service name="createCustomerPostalAddress"/>
    </operation>
    <operation verb="post" path="/{customerPartyId}/shipping-addresses" description="Creates shipping address">
      <service name="createCustomerPostalAddress"/>
    </operation>
    <operation verb="put" path="/{customerPartyId}/shipping-addresses/{contactMechId}" description="Updates shipping address">
      <service name="updateCustomerPostalAddress"/>
    </operation>
    <operation verb="post" path="/{customerPartyId}/change-password" description="Changes customer's account password">
      <service name="changePassword"/>
    </operation>
    <operation verb="post" path="/reset-password" description="Sends reset password mail">
      <service name="sendResetPasswordEmail"/>
    </operation>
    <operation verb="delete" path="/{customerPartyId}/shipping-addresses/{contactMechId}" description="Expires shipping address">
      <service name="removeCustomerContactMech"/>
    </operation>
    <operation verb="get" path="/{customerPartyId}/payment-methods" description="Get payment methods(credit card, gift card, eft account)">
      <service name="getPartyPaymentMethods"/>
    </operation>
    <operation verb="post" path="/{customerPartyId}/payment-methods" description="Creates payment method(credit card, gift card, eft account)">
      <service name="createCustomerPaymentMethod"/>
    </operation>
    <operation verb="put" path="/{customerPartyId}/payment-methods/{paymentMethodId}" description="Updates payment method(credit card, gift card, eft account)">
      <service name="updateCustomerPaymentMethod"/>
    </operation>
    <operation verb="delete" path="/{customerPartyId}/payment-methods/{paymentMethodId}" description="Deletes payment method(credit card, gift card, eft account)">
      <service name="deleteCustomerPaymentMethod"/>
    </operation>
  </resource>
</api>
